# Basic values.yaml for Kong for Kubernetes with Kong Enterprise
# Several settings (search for the string "you-must") require user-provided
# Secrets. These Secrets must be created before installation.
#
# This installation does not create an Ingress or LoadBalancer Service for
# the Admin API. It requires port-forwards to access without further
# configuration to add them, e.g.:
# kubectl port-forward deploy/your-deployment-kong 8001:8001

image:
  repository: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition
  tag: 1.5.0.2-alpine
  pullSecrets:
    # you-must add this: https://github.com/Kong/charts/blob/master/charts/kong/README.md#kong-enterprise-docker-registry-access
    - kong-enterprise-edition-docker

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001

enterprise:
  enabled: true
  license_secret: you-must-create-a-license-secret
  vitals:
    enabled: false
  portal:
    enabled: false
  rbac:
    enabled: false
  smtp:
    enabled: false

env:
  prefix: /kong_prefix/
  database: postgres
  password:
    valueFrom:
      secretKeyRef:
        name: you-must-create-an-rbac-bootstrap-secret
        key: you-must-replace-with-your-key

postgresql:
  enabled: true
  postgresqlUsername: kong
  postgresqlDatabase: kong
  service:
    port: 5432

ingressController:
  enabled: true
  installCRDs: false
