apiVersion: v2
description: Deploy Kong Ingress Controller and Kong Gateway
home: https://konghq.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
maintainers:
  - name: team-k8s-bot
    email: team-k8s@konghq.com
name: ingress
sources:
  - https://github.com/Kong/charts/tree/main/charts/ingress
version: 0.8.0
appVersion: "3.4"
dependencies:
  - name: kong
    version: ">=2.30.0"
    repository: https://charts.konghq.com
    alias: controller
    condition: controller.enabled
  - name: kong
    version: ">=2.30.0"
    repository: https://charts.konghq.com
    alias: gateway
    condition: gateway.enabled
