image:
  # repository: kong-docker-kong-brain-immunity-base.bintray.io/kong-brain-immunity
  # tag: latest
  pullPolicy: IfNotPresent
  repository: kong-docker-kong-brain-internal-builds.bintray.io/kong-brain
  tag: master

imagePullSecrets:
  # - name: bintray-kong-brain-immunity
  - name: bintray-kong-brain-internal

waitImage:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent

kongAdmin:
  # Set this to the Kong Admin API hostname
  host: my-kong-kong-admin
  # Set this to the Kong Admin API port
  servicePort: 8001
  # Set this to the Kong Admin API protocol
  Protocol: http

collector:
  containerPort: 5000
  # Set a nodePort which is available
  nodePort: 31555
  service:
    type: NodePort
    port: 5000

postgresql:
  enabled: true
  postgresqlUsername: collector
  postgresqlPassword: collector
  postgresqlDatabase: collector
  service:
    port: 5432

redis:
  enabled: true
  port: 6379
  password: redis

ingress:
  enabled: false

# Enable this for running integration tests
testendpoints:
  enabled: false
