ko-crds:
  enabled: false

podAnnotations:
  key: value

livenessProbe:
  initialDelaySeconds: 1
  periodSeconds: 1

readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 1

env:
  anonymous_reports: "false"
