livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 1
  periodSeconds: 1
readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 1
args:
  - --zap-log-level=debug
env:
  anonymous_reports: "false"
  no_leader_election: "true"
