{{- define "kong.certificate.issuer" -}}
{{- printf "%s-%s-%s" .Release.Name .Chart.Name "selfsigned-issuer" -}}
{{- end -}}
{{- if and ( .Capabilities.APIVersions.Has "cert-manager.io/v1" ) .Values.certificates.enabled .Values.certificates.portal.enabled }}
# Kong Developer Portal Certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kong.fullname" . }}-portal-cert
  namespace:  {{ template "kong.namespace" . }}
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
spec:
  secretName: {{ include "kong.fullname" . }}-portal-cert
  commonName: {{ .Values.certificates.portal.commonName }}
  dnsNames:
  - {{ .Values.certificates.portal.commonName }}
  {{- range .Values.certificates.portal.dnsNames }}
  - {{ . | quote }}
  {{- end }}
  renewBefore: 360h
  duration: 2160h
  isCA: false
  {{ if .Values.certificates.portal.clusterIssuer }}
  issuerRef:
    name: {{ .Values.certificate.portal.clusterIssuer }}
    kind: clusterIssuer
  {{ else if .Values.certificates.portal.issuer }}
  issuerRef:
    name: {{ .Values.certificate.portal.issuer }}
    kind: Issuer
  {{ else if .Values.certificates.clusterIssuer }}
  issuerRef:
    name: {{ .Values.certificate.clusterIssuer }}
    kind: clusterIssuer
  {{ else if .Values.certificates.issuer }}
  issuerRef:
    name: {{ .Values.certificate.issuer }}
    kind: Issuer
  {{ else }}
  issuerRef:
    name: {{ template "kong.builtin.issuerName" . }}
    kind: Issuer
  {{- end -}}
{{- end }}