{{- if .Values.deployment.kong.enabled }}
{{- if .Release.IsInstall -}}
{{/* .migrations.init isn't normally exposed in values.yaml, since it should
     generally always run on install--there should never be any reason to
     disable it, and at worst it's a no-op. However, https://github.com/helm/helm/issues/3308
     means we cannot use the default function to create a hidden value, hence
     the workaround with this $runInit variable.
 */}}
{{- $runInit := true -}}
{{- if (hasKey .Values.migrations "init") -}}
  {{- $runInit = .Values.migrations.init -}}
{{- else if (hasKey .Values "runMigrations") -}}
  {{- $runInit = .Values.runMigrations -}}
{{- end -}}

{{- if (and ($runInit) (not (eq .Values.env.database "off"))) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kong.fullname" . }}-init-migrations
  namespace: {{ template "kong.namespace" . }}
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: init-migrations
  {{- range $key, $value := .Values.migrations.jobAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  template:
    metadata:
      name: {{ template "kong.name" . }}-init-migrations
      labels:
        {{- include "kong.metaLabels" . | nindent 8 }}
        app.kubernetes.io/component: init-migrations
      {{- if .Values.migrations.annotations }}
      annotations:
      {{- range $key, $value := .Values.migrations.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    spec:
      {{- if .Values.podSecurityPolicy.enabled }}
      serviceAccountName: {{ template "kong.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      initContainers:
      {{- if (eq .Values.env.database "postgres") }}
      {{- include "kong.wait-for-postgres" . | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ template "kong.name" . }}-migrations
        {{- if .Values.image.unifiedRepoTag }}
        image: "{{ .Values.image.unifiedRepoTag }}"
        {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- include "kong.no_daemon_env" . | nindent 8 }}
        command: [ "/bin/sh", "-c", "kong migrations bootstrap" ]
        volumeMounts:
        {{- include "kong.volumeMounts" . | nindent 8 }}
      securityContext:
      {{- include "kong.podsecuritycontext" . | nindent 8 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      volumes:
      {{- include "kong.volumes" . | nindent 6 -}}
{{- end }}
{{- end }}
{{- end }}
