{{- if and ( .Capabilities.APIVersions.Has "cert-manager.io/v1" ) .Values.certificate.proxy.enabled }}
# Kong Proxy Certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kong.fullname" . }}-kong-cert
  namespace:  {{ template "kong.namespace" . }}
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
spec:
  secretName: {{ include "kong.fullname" . }}-kong-cert
  commonName: kong_clustering
  dnsNames:
  {{- range .Values.certificate.dnsNames }}
  - {{ . | quote }}
  {{- end }}
  renewBefore: 360h
  duration: 2160h
  isCA: false
  issuerRef:
    name: {{ template "kong.certificate.issuer" . }}
    kind: ClusterIssuer
{{- end }}