apiVersion: v2
description: Deploy Kong Operator
home: https://konghq.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
maintainers:
  - name: team-k8s-bot
    email: team-k8s@konghq.com
name: kong-operator
sources:
  - https://github.com/Kong/kong-operator/charts/kong-operator/
version: 1.2.1
appVersion: "2.1.1"
annotations:
  artifacthub.io/category: networking
  artifacthub.io/prerelease: "false"
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Seamless Upgrades
  artifacthub.io/links: |
    - name: Documentation
      url: https://developer.konghq.com/operator/
    - name: Repository
      url: https://github.com/Kong/kong-operator
dependencies:
  - name: ko-crds
    version: 1.0.1
  - name: gwapi-standard-crds
    version: 1.4.1
    condition: gwapi-standard-crds.enabled
  - name: gwapi-experimental-crds
    version: 1.4.1
    condition: gwapi-experimental-crds.enabled
