admin:
  enabled: true
  type: ClusterIP

# Stub config to make the instance become ready
dblessConfig:
  config: |
    _format_version: "1.1"
    services:
    - name: example.com
      url: http://example.com
      routes:
      - name: example
        paths:
        - "/example"

ingressController:
  enabled: false

# NOTE: The purpose of those values below is to:
# - to speed up, the test
# - to prevent anonymous reports from being sent
readinessProbe:
  httpGet:
    scheme: HTTP
  initialDelaySeconds: 1
  periodSeconds: 1

env:
  anonymous_reports: "off"
