# install chart with default values

# NOTE: The purpose of those values below is to:
# - to speed up, the test
# - to prevent anonymous reports from being sent
readinessProbe:
  httpGet:
    path: "/status"
    port: status
    scheme: HTTP
  initialDelaySeconds: 1
  periodSeconds: 1

env:
  anonymous_reports: "off"

ingressController:
  env:
    anonymous_reports: "false"
