# CI test for using ingress hosts configuration
proxy:
  ingress:
    enabled: true
    hosts:
    - host: proxy.kong.example
      paths:
      - path: /
        pathType: ImplementationSpecific

# NOTE: The purpose of those values below is to:
# - to speed up, the test
# - to prevent anonymous reports from being sent
readinessProbe:
  httpGet:
    scheme: HTTP
  initialDelaySeconds: 1
  periodSeconds: 1

env:
  anonymous_reports: "off"

ingressController:
  env:
    anonymous_reports: "false"
