
# install chart with a service account
deployment:
  serviceAccount:
    create: true
    name: "my-kong-sa"
    annotations: {}

ingressController:
  serviceAccount:
    create: false
  deployment:
    pod:
      container:
        env:
          anonymous_reports: "false"

# NOTE: The purpose of those values below is to:
# - to speed up, the test
# - to prevent anonymous reports from being sent
readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 1

env:
  anonymous_reports: "off"
