# install chart with default values
# use single image strings instead of repository/tag

image:
  unifiedRepoTag: kong:3.7

env:
  anonymous_reports: "off"
ingressController:
  deployment:
    pod:
      container:
        env:
          anonymous_reports: "false"
        image:
          unifiedRepoTag: kong/kubernetes-ingress-controller:3.6
        # NOTE: The purpose of those values below is to:
        # - to speed up, the test
        # - to prevent anonymous reports from being sent
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 1

# NOTE: The purpose of those values below is to:
# - to speed up, the test
# - to prevent anonymous reports from being sent
readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 1
