apiVersion: v2
description: The Cloud-Native Ingress and API-management
home: https://konghq.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
maintainers:
  - name: team-k8s-bot
    email: team-k8s@konghq.com
name: kong
sources:
  - https://github.com/Kong/charts/tree/main/charts/kong
version: 2.37.0
appVersion: "3.6"
dependencies:
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
