apiVersion: v2
description: The Cloud-Native Ingress and API-management
engine: gotpl
home: https://konghq.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
maintainers:
- name: hbagdi
  email: harry@konghq.com
- name: rainest
  email: traines@konghq.com
name: kong
sources:
version: 2.7.0
appVersion: "2.8"
dependencies:
- name: postgresql
  version: 11.1.15
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
